### ISSUE TITLE
ch12 dense_mapping.cpp中极线搜索遇到的小问题

### ISSUE THREAD

**Issue by LuckySquirrel** [gaoxiang12/slambook2#119]
![image](https://user-images.githubusercontent.com/30206054/93288972-b0a4a700-f80f-11ea-9beb-9b8921423d50.png)
请问倒数第二行中为什么要将归一化坐标normalize？如果不做这一步会有什么影响吗？

**Comment by BiaoBiaoLi** [comment]
楼主你知道了吗谢谢

**Comment by LuckySquirrel** [comment]
> 

学习了，谢谢dalao解答

**Comment by LuckySquirrel** [comment]
> 应该是因为，这个地方的深度值是整个（x,y,z）的模长，所以和之前公式看起来有点不一样，应该也可以根据（x/z，y/z，1）来求解吧，求出的是z

学习了，谢谢dalao解答

**Comment by LuckySquirrel** [comment]
> 应该是因为，这个地方的深度值是整个（x,y,z）的模长，所以和之前公式看起来有点不一样，应该也可以根据（x/z，y/z，1）来求解吧，求出的是z

学习了，谢谢dalao解答
