### ISSUE TITLE
ch7 Ubuntu18.04中编译orb_self.cpp 时出错了

### ISSUE THREAD

**Issue by Zhouxijun** [gaoxiang12/slambook2#121]
orb_self.cpp: In function ‘void BfMatch(const std::vector<std::vector<unsigned int> >&, const std::vector<std::vector<unsigned int> >&, std::vector<cv::DMatch>&)’:
orb_self.cpp:402:28: warning: narrowing conversion of ‘i1’ from ‘size_t {aka long unsigned int}’ to ‘int’ inside { } [-Wnarrowing]
     cv::DMatch m{i1, 0, 256};
                            ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:811:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/7/include/nmmintrin.h:31,
                 from orb_self.cpp:7:
/usr/lib/gcc/x86_64-linux-gnu/7/include/popcntintrin.h:35:1: error: inlining failed in call to always_inline ‘int _mm_popcnt_u32(unsigned int)’: target specific option mismatch
 _mm_popcnt_u32 (unsigned int __X)
 ^~~~~~~~~~~~~~
orb_self.cpp:407:35: note: called from here
         distance += _mm_popcnt_u32(desc1[i1][k] ^ desc2[i2][k]);
                     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by IshitaB28** [comment]
Could you please tell me how you resolved this issue?
