### ISSUE TITLE
Chapter 11. Missing ***associate.txt*** in program ***gen_vocab_large.cpp***

### ISSUE THREAD

**Issue by SupremeDing1996** [gaoxiang12/slambook2#13]
missing associate.txt file in ch11 dir which is need in gen_vocab_large.cpp
`    string dataset_dir = argv[1];
       ifstream fin ( dataset_dir+"/**associate.txt**" );
`

**Comment by gaoxiang12** [comment]
Please follow TUM RGB-D dataset [link](https://vision.in.tum.de/data/datasets/rgbd-dataset/tools) to get the associate.txt. It's just a text file indicating the rgb and depth image pairs.

**Comment by SupremeDing1996** [comment]
Thank you very much!

**Comment by resplendent-star** [comment]
> 非常感谢你！

你好,能发一下具体网址吗,我在高老师提供的网址上面没找到:P
