### ISSUE TITLE
怎么通过git submodule 安装第三方库呢

### ISSUE THREAD

**Issue by martino92** [gaoxiang12/slambook2#139]
如题，ch3遇到pangolin不知道怎么安装

**Comment by robin-shaun** [comment]
git submodule init
git submodule update
然后看pangolin的readme安装

**Comment by gaoxiang12** [comment]
请参考本楼中回复。
关闭本issue，如有需要请重新打开 @martino92

**Comment by Tokymin** [comment]
> 
> 
> 如题，ch3遇到pangolin不知道怎么安装

我也是请问解决了嘛
