### ISSUE TITLE
ch13

### ISSUE THREAD

**Issue by zhouyazhoulearn** [gaoxiang12/slambook2#14]
您好，不知道您是否讲位姿输出到文件，我已仔细查看了轨迹输出应该是没问题的。我用同一个数据集（odo的03）跑了您的ch13和ORBSLAM2,对比ORBSLAM2的轨迹，这ch13输出的轨迹很乱，比如ch13估计平移的x值，ORBSLAM2一直是增加的，可ch13估计平移的x值却增增减减，呈波浪状。期待您的回复，谢谢

**Comment by gaoxiang12** [comment]
请说明具体的数据集名称和现象，这些信息无法推断原因。

**Comment by zhouyazhoulearn** [comment]
接下来我分别上传使用evo（tum）生成的轨迹图  :  ch13跑200帧KITTI/data_odometry_gray/03  ；ch13,跑800帧KITTI/data_odometry_gray/03   ；   ORBSLAM2跑800帧KITTI/data_odometry_gray/03
![200zhen_image_trajectories](https://user-images.githubusercontent.com/45961197/64011873-1d8ac780-cb4f-11e9-9f34-ed2eeb3c9f4e.png)
![200zhen_image_xyx_view](https://user-images.githubusercontent.com/45961197/64011930-35624b80-cb4f-11e9-880b-c663f1581ffe.png)
![200zhen_image_rpy_view](https://user-images.githubusercontent.com/45961197/64011941-3bf0c300-cb4f-11e9-973c-0bb3aa9edda6.png)

ch13,跑800帧KITTI/data_odometry_gray/03   ；
![800zhen_trajectories](https://user-images.githubusercontent.com/45961197/64012049-82deb880-cb4f-11e9-9f35-8e92c86cb0fb.png)
![800zhen_xyz_view](https://user-images.githubusercontent.com/45961197/64012058-870ad600-cb4f-11e9-9333-696f6928ca77.png)
![800zhen_rpy_view](https://user-images.githubusercontent.com/45961197/64012073-8bcf8a00-cb4f-11e9-8655-862e27bb87a4.png)

ORBSLAM2跑800帧KITTI/data_odometry_gray/03
![ORBSLAM2_trajectories](https://user-images.githubusercontent.com/45961197/64012108-a1dd4a80-cb4f-11e9-8b3a-5e2c21e7f974.png)
![ORBSLAM2_xyz_view](https://user-images.githubusercontent.com/45961197/64012122-a73a9500-cb4f-11e9-8f04-ed3999389fe4.png)
![ORBSLAM2_rpy_view](https://user-images.githubusercontent.com/45961197/64012278-f08ae480-cb4f-11e9-8b9f-134eb3e38b3f.png)
麻烦您了，谢谢

**Comment by zhouyazhoulearn** [comment]
已经找到原因，仔细查看了输出文件代码，文件每行格式信息中的平移部分获取时少了一行变换矩阵的“”逆求解“”应该是“”所求变换矩阵的逆，再取平移部分即Twr中的平移部分，而不是Trw中的平移部分“”
