### ISSUE TITLE
The return value of triangulation function is possibly wrong

### ISSUE THREAD

**Issue by NERanger** [gaoxiang12/slambook2#143]
In ch13/include/myslam/algorithm.h

```cpp
/**
 * linear triangulation with SVD
 * @param poses     poses,
 * @param points    points in normalized plane
 * @param pt_world  triangulated point in the world
 * @return true if success
 */
inline bool triangulation(const std::vector<SE3> &poses,
                   const std::vector<Vec3> points, Vec3 &pt_world) {
    MatXX A(2 * poses.size(), 4);
    VecX b(2 * poses.size());
    b.setZero();
    for (size_t i = 0; i < poses.size(); ++i) {
        Mat34 m = poses[i].matrix3x4();
        A.block<1, 4>(2 * i, 0) = points[i][0] * m.row(2) - m.row(0);
        A.block<1, 4>(2 * i + 1, 0) = points[i][1] * m.row(2) - m.row(1);
    }
    auto svd = A.bdcSvd(Eigen::ComputeThinU | Eigen::ComputeThinV);
    pt_world = (svd.matrixV().col(3) / svd.matrixV()(3, 3)).head<3>();

    if (svd.singularValues()[3] / svd.singularValues()[2] < 1e-2) {
        // 解质量不好，放弃
        return true;
    }
    return false;
}
```

The docs says that this function should return true if success, but in the implementation, true is returned when discarding the solution. Is this a bug or I am understanding it wrongly?

**Comment by NERanger** [comment]
I see that `svd.singularValues()[3] / svd.singularValues()[2] < 1e-2` as a test for condition number. My understanding of the code is that **if the condition number is below 1e-2, then the solution is considered to be good**. But still I have some confusion:

- Is the comment here misleading?
- Condition number is the ration of its largest singular value to the smallest singular value. The larger the number is, the more the matrix is considered as ill-conditioned. Since the singular values are sorted in decreasing order, `svd.singularValues()[3]` is the smallest and `svd.singularValues()[2]` is a middle value. This is more like a reciprocal of condition number and makes no sense to me. Is this a empirical test?

**Comment by NERanger** [comment]
Let me be more precise:

If `svd.singularValues()[3] / svd.singularValues()[2]` is seen as a reciprocal of condition number, then the solution is considered t be bad when the value is small. If so, the funtion should return false when `svd.singularValues()[3] / svd.singularValues()[2] < 1e-2` is false.

**Comment by zhaoworking** [comment]
> Let me be more precise:
> 
> If `svd.singularValues()[3] / svd.singularValues()[2]` is seen as a reciprocal of condition number, then the solution is considered t be bad when the value is small. If so, the funtion should return false when `svd.singularValues()[3] / svd.singularValues()[2] < 1e-2`.

Have u figured out what is going on here? i'm also confused why the condition should be this.

**Comment by NERanger** [comment]
Feel free to reopen the issue if you need.

**Comment by yuhuihao** [comment]
The least squares solution is the right singular vector corresponding to the smallest singular value. If the smallest singular value is not much smaller than the penultimate smallest singular value (by two orders of magnitude), the solution is considered to be of bad quality. So I think the code is fine, but the comment is wrong.
