### ISSUE TITLE
Jacobian calculation in slambook2/ch6/g2oCurveFitting.cpp

### ISSUE THREAD

**Issue by nicolasrosa** [gaoxiang12/slambook2#144]
Hello @gaoxiang12,

I finished reading Chapter 6, but I still have some doubts about how the following code works. How did you calculate the Jacobians in the following function? Which equation in the book was used?

`slambook2/ch6/g2oCurveFitting.cpp`

```cpp
virtual void linearizeOplus() override {
    const CurveFittingVertex *v = static_cast<const CurveFittingVertex *> (_vertices[0]);
    const Eigen::Vector3d abc = v->estimate();
    double y = exp(abc[0] * _x * _x + abc[1] * _x + abc[2]);
    _jacobianOplusXi[0] = -_x * _x * y;
    _jacobianOplusXi[1] = -_x * y;
    _jacobianOplusXi[2] = -y;
  }
```
Equations:

![CodeCogsEqn (1)](https://user-images.githubusercontent.com/7122146/107701028-139f4a80-6c97-11eb-8f6a-ea44d2b7c600.gif)

`_jacobianOplusXi` corresponds to the first derivative (Jacobian) of each parameter being estimated (`a,b,c`), correct? 

What about the `negative sign`? Do we just say that we want to update `a,b,c` with its negative gradient?

In this case, we haven't calculated the Hessian, `H(x)`, correct? We just have plugged the negative Jacobian, `-J(x)`, in the variable `_jacobianOplusXi`, we aren't plugging `g(x)`, correct?

**Comment by gaoxiang12** [comment]
Hi @nicolasrosa ,

1. Yes _jacobianOplusXi is the Jacobian of d(error)/d(a,b,c) here. Note that the error is computed as erro=y-exp(ax^2 +bx +c): https://github.com/gaoxiang12/slambook2/blob/9382d9066029308ff40a539d64880d540135bfd6/ch6/g2oCurveFitting.cpp#L49.
2. This brings the negative sign in the Jacobian. In other words, we have d(error)/d(a) = -x^2 y. We don't need to manually add a negative sign to represent the negative gradient. Ceres/g2o will do this.
3. We don't need to calculate Hessian by ourselves. Ceres/g2o will approximate the Hessian with G-N/L-M/Dogleg solvers.

Hope this can help you.

I'm doing a grammar check from chapter 2 again. Chapters 7 and 8 are translated by Carrie and I think it is not ready to read for now.

**Comment by nicolasrosa** [comment]
@gaoxiang12 Thank you for your prompt reply!

Oh, I see now, I was thinking that `f(x)` corresponded just to the exponential part, but, in fact, it's the whole error equation, `e(x
)`. As you said that explains the `negative sign` in the jacobians.

![CodeCogsEqn (1)](https://user-images.githubusercontent.com/7122146/107771597-bb5d5c80-6d19-11eb-9d45-6cf9aeeb734f.gif)

**Comment by gaoxiang12** [comment]
Yes, and g2o will put the information matrix into the squared error. The final cost function is the sum of the squared errors.
Normally we use the word "_error_" or "_residual_" for the raw error (without square) and use the word "_cost_" for the squared. Sometimes the word "_loss_" is used for "_cost_" with a robust kernel function.
