### ISSUE TITLE
ch3 中make一步报错，具体好像是isometry3d等库函数没有声明？（报错提示如下）

### ISSUE THREAD

**Issue by xiaohuozi-code** [gaoxiang12/slambook2#147]
xiaotudou@xiaotudou-virtual-machine:~/slambook2/ch3/examples/build$ make
Scanning dependencies of target coordinateTransform
[ 25%] Building CXX object CMakeFiles/coordinateTransform.dir/coordinateTransform.cpp.o
[ 50%] Linking CXX executable coordinateTransform
[ 50%] Built target coordinateTransform
Scanning dependencies of target plotTrajectory
[ 75%] Building CXX object CMakeFiles/plotTrajectory.dir/plotTrajectory.cpp.o
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:12:28: error: ‘Isometry3d’ was not declared in this scope
 void DrawTrajectory(vector<Isometry3d, Eigen::aligned_allocator<Isometry3d>>);
                            ^~~~~~~~~~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:12:65: error: ‘Isometry3d’ was not declared in this scope
 void DrawTrajectory(vector<Isometry3d, Eigen::aligned_allocator<Isometry3d>>);
                                                                 ^~~~~~~~~~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:12:65: error: template argument 1 is invalid
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:12:75: error: template argument 1 is invalid
 void DrawTrajectory(vector<Isometry3d, Eigen::aligned_allocator<Isometry3d>>);
                                                                           ^~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:12:75: error: template argument 2 is invalid
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp: In function ‘int main(int, char**)’:
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:16:10: error: ‘Isometry3d’ was not declared in this scope
   vector<Isometry3d, Eigen::aligned_allocator<Isometry3d>> poses;
          ^~~~~~~~~~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:16:47: error: type/value mismatch at argument 1 in template parameter list for ‘template<class T> class Eigen::aligned_allocator’
   vector<Isometry3d, Eigen::aligned_allocator<Isometry3d>> poses;
                                               ^~~~~~~~~~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:16:47: note:   expected a type, got ‘Isometry3d’
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:16:57: error: template argument 1 is invalid
   vector<Isometry3d, Eigen::aligned_allocator<Isometry3d>> poses;
                                                         ^~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:16:57: error: template argument 2 is invalid
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:26:16: error: expected ‘;’ before ‘Twr’
     Isometry3d Twr(Quaterniond(qw, qx, qy, qz));
                ^~~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:27:5: error: ‘Twr’ was not declared in this scope
     Twr.pretranslate(Vector3d(tx, ty, tz));
     ^~~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:28:11: error: request for member ‘push_back’ in ‘poses’, which is of non-class type ‘int’
     poses.push_back(Twr);
           ^~~~~~~~~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:30:34: error: request for member ‘size’ in ‘poses’, which is of non-class type ‘int’
   cout << "read total " << poses.size() << " pose entries" << endl;
                                  ^~~~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp: At global scope:
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:38:28: error: ‘Isometry3d’ was not declared in this scope
 void DrawTrajectory(vector<Isometry3d, Eigen::aligned_allocator<Isometry3d>> poses) {
                            ^~~~~~~~~~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:38:65: error: ‘Isometry3d’ was not declared in this scope
 void DrawTrajectory(vector<Isometry3d, Eigen::aligned_allocator<Isometry3d>> poses) {
                                                                 ^~~~~~~~~~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:38:65: error: template argument 1 is invalid
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:38:75: error: template argument 1 is invalid
 rawTrajectory(vector<Isometry3d, Eigen::aligned_allocator<Isometry3d>> poses) {
                                                                     ^~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:38:75: error: template argument 2 is invalid
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp: In function ‘void DrawTrajectory(int)’:
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:59:34: error: request for member ‘size’ in ‘poses’, which is of non-class type ‘int’
     for (size_t i = 0; i < poses.size(); i++) {
                                  ^~~~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:61:28: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript
       Vector3d Ow = poses[i].translation();
                            ^
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:62:28: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript
       Vector3d Xw = poses[i] * (0.1 * Vector3d(1, 0, 0));
                            ^
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:63:28: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript
       Vector3d Yw = poses[i] * (0.1 * Vector3d(0, 1, 0));
                            ^
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:64:28: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript
       Vector3d Zw = poses[i] * (0.1 * Vector3d(0, 0, 1));
                            ^
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:78:34: error: request for member ‘size’ in ‘poses’, which is of non-class type ‘int’
     for (size_t i = 0; i < poses.size(); i++) {
                                  ^~~~
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:81:24: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript
       auto p1 = poses[i], p2 = poses[i + 1];
                        ^
/home/xiaotudou/slambook2/ch3/examples/plotTrajectory.cpp:83:18: error: ‘p2’ was not declared in this scope
       glVertex3d(p2.translation()[0], p2.translation()[1], p2.translation()[2]);
                  ^~
CMakeFiles/plotTrajectory.dir/build.make:62: recipe for target 'CMakeFiles/plotTrajectory.dir/plotTrajectory.cpp.o' failed
make[2]: *** [CMakeFiles/plotTrajectory.dir/plotTrajectory.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/plotTrajectory.dir/all' failed
make[1]: *** [CMakeFiles/plotTrajectory.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gaoxiang12** [comment]
把 <Eigen/Geometry> 引进来就可以了

**Comment by xiaohuozi-code** [comment]
> 把 <Eigen/Geometry> 引进来就可以了

谢谢 已解决

**Comment by Livesoso** [comment]
我还以为版本的问题，气死，感谢感谢
