### ISSUE TITLE
ch7中的pose_estimation_3d2d和pose_estimation_3d3d 运行时出现错误

### ISSUE THREAD

**Issue by liangsy98** [gaoxiang12/slambook2#149]
在ubuntu16.04中运行ch7中的代码时出现以下错误：
[ 50%] Building CXX object CWakeFiles/pose_estimation_3d3d .dir/pose_estimation_3d3d.cpp.o
In file included from /usr/locaL/include/q2o/core/base_unary_edqe.h:30:0,
                         from /home/liangshaoyang/shenlan/slambook2/ch7/pose_estimation_3d3d.cpp:11:
/usr/local/include/g2o/core/base _fixed _sized_edge.h:174:27: error:‘index_sequence’is not a member of 'std“
struct HessianTupleType<std : :index_sequence<Ints...>> {

/usr/local/include/g2o/core/base_fixed_sized_edge.h:174:27: error:‘index_sequence’is not a member of ‘std'
/usr/local/include/q2o/core/base_fixed_sized_edge.h:174:51: error: expected parameter pack before '...'
struct HessianTupleType<std : :index_sequence<Ints...>> {
/usr/local/include/g2o/core/base_fixed_sized_edge.h:174:51: error: template argument 1 is invalid
/usr/local/include/ g2o/core/base _fdixed_sized_edge.h:174:;54: error: expected unqualified-id before '>' token
struct HessianTupleType<std : :index_sequence<Ints.. .>> {
/usr/local/include/g2o/core/base_fixed_sized_edge.h:181:33: error: ‘'make_index_sequence’is not a member of 'std'
typename HessianTupleType<std ::make_index_sequence<_nr_of_vertex_pairs>>: :type;
不知道是什么地方的原因，希望老师给予一些指导。

**Comment by gaoxiang12** [comment]
看网上建议是在cmake里更新到14标准试试？
可以直接 SET_CMAKE_STANDARD(14) 或者在编译器flags里设置为-std=c++14

**Comment by liangsy98** [comment]
问题已经解决，感谢老师的指导！
