### ISSUE TITLE
CH3 关于eigenMatrix.cpp的可能的问题

### ISSUE THREAD

**Issue by LongruiDong** [gaoxiang12/slambook2#15]
你好 高博，
我在实验eigenMatrix.cpp代码时，发现两个疑惑的问题，若自己搞错了，也请大家指正～
### 1
```
Matrix<double, MATRIX_SIZE, MATRIX_SIZE> matrix_NN
      = MatrixXd::Random(MATRIX_SIZE, MATRIX_SIZE);
```
我运行多次，发现这里返回的matrix_NN都一样，然后根据[这里](https://stackoverflow.com/a/21294746/9641752)，得到了真正每次都随机生成不同矩阵

### 2
```
matrix_NN = matrix_NN * matrix_NN.transpose();  // 保证半正定
```
我记得实对称矩阵不一定半正定或正定吧？
但是在多次运行后（不同的matrix_NN和v_Nd），发现这里后面的cholesky分解来解方程也一直没问题，不是只有正定矩阵才能用该方法吗？

谢谢！

**Comment by cowant** [comment]
关于第二点:
matrix_NN是一个方阵与其转置的乘积，是实对称矩阵且半正定的，因为对于任意的方阵A:

<img src="https://latex.codecogs.com/gif.latex?x^{T}A^{T}Ax&space;&=&space;(Ax)^{T}(Ax)&space;\geq&space;0\\&space;(A^{T}A)^{T}&space;&=&space;A^{T}A" title="x^{T}A^{T}Ax &= (Ax)^{T}(Ax) \geq 0\\ (A^{T}A)^{T} &= A^{T}A" />
那么说明A的转置与A的乘积得到的矩阵是实对称矩阵且半正定的。

根据Eigen的文档[LDLT模板类](http://eigen.tuxfamily.org/dox/classEigen_1_1LDLT.html):
```bash
Perform a robust Cholesky decomposition of a positive semidefinite or negative semidefinite matrix...
```
Eigen对于半正定矩阵也是可以进行Cholesky分解的。

**Comment by LongruiDong** [comment]
> 关于第二点:
> matrix_NN是一个方阵与其转置的乘积，是实对称矩阵且半正定的，因为对于任意的方阵A:
> 
> ![](https://camo.githubusercontent.com/972116161d7a8d84954eaf78e6966b015a732284/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f785e7b547d415e7b547d41782673706163653b263d2673706163653b284178295e7b547d284178292673706163653b5c6765712673706163653b305c5c2673706163653b28415e7b547d41295e7b547d2673706163653b263d2673706163653b415e7b547d41)
> 
> 那么说明A的转置与A的乘积得到的矩阵是实对称矩阵且半正定的。
> 根据Eigen的文档[LDLT模板类](http://eigen.tuxfamily.org/dox/classEigen_1_1LDLT.html):
> 
> ```shell
> Perform a robust Cholesky decomposition of a positive semidefinite or negative semidefinite matrix...
> ```
> 
> Eigen对于半正定矩阵也是可以进行Cholesky分解的。

感谢 !~
懂了O(∩_∩)O哈哈哈~
