### ISSUE TITLE
ch6第133页公式6.41疑问

### ISSUE THREAD

**Issue by mli0603** [gaoxiang12/slambook2#157]
请问下高翔老师和各位小伙伴,

我有一个对于最小二乘问题，当有很多项的时候，我的理解是我们需要把所有的Hessian和Jacobian列出来，比如在ch6第133页的例子里面，我想到的是去解
![image](https://user-images.githubusercontent.com/13513172/112888051-e3263b00-90a1-11eb-95dd-f7d5146a1bce.png)

在公式6.41中，Hessian直接被加了起来，在解释中说的是这样和上面的结果是等效的。我不太理解这两个结果为什么是等效的，希望可以帮忙解释一下。非常感谢！
![image](https://user-images.githubusercontent.com/13513172/112888466-621b7380-90a2-11eb-81a3-7e2f151cec90.png)

**Comment by gaoxiang12** [comment]
hi @mli0603 ,
这个例子中，每个残差是1维的，自变量是3维的，并且每个残差都和自变量有关。目标函数是所有残差的平方和，也是一维的。所以在Jacobian的计算中，应该是把各个Jacobian加起来哦。你列写的上面式子是不对的。
如果问题维度较高，使得某个残差只和一部分自变量相关，那么存在两种做法：
1. 只计算残差与相关的自变量的Jacobian，那么这种Jacobian是很小的，最后我们求和来计算对应的那一块Hessian。
2. 计算残差对所有自变量的Jacobian，此时Jacobian是残差维度*自变量维度，是稀疏的。那么可以用它来拼成整个Hessian，但实际只有对应的那一块Hessian有非零值。
所以在这个意义上，两种做法得到的最终Hessian是一样的。

**Comment by mli0603** [comment]
@gaoxiang12, 感谢高翔老师，我现在理解相加的计算和如何得到Hessian的部分了，非常感谢！

另外在128页公式6.30下面，说道`J(x)^T`为`nx1`的向量，但是书中大部分的公式都是以`J(x)`为`nx1`的向量写的，比如说6.26
![image](https://user-images.githubusercontent.com/13513172/113007183-fd185a00-9143-11eb-8404-66fd6fc20cf8.png)

128页公式6.30下面这句话这个貌似是个笔误。
