### ISSUE TITLE
ch3 useGeometry在ubuntu18.04，clion下进行编译出错

### ISSUE THREAD

**Issue by xhyu1** [gaoxiang12/slambook2#16]
====================[ Build | eigenGeometry | Debug ]===========================
/snap/clion/82/bin/cmake/linux/bin/cmake --build /home/xhyu/slambook2/ch3/useGeometry/cmake-build-debug --target eigenGeometry -- -j 6
Scanning dependencies of target eigenGeometry
[ 33%] Building CXX object CMakeFiles/eigenGeometry.dir/home/xhyu/slambook2/ch3/examples/coordinateTransform.cpp.o
[ 66%] Linking CXX executable eigenGeometry
CMakeFiles/eigenGeometry.dir/home/xhyu/slambook2/ch3/examples/coordinateTransform.cpp.o: In function `main':
/usr/include/eigen3/Eigen/src/Core/IO.h:129: multiple definition of `main'
CMakeFiles/eigenGeometry.dir/eigenGeometry.cpp.o:/home/xhyu/slambook2/ch3/useGeometry/eigenGeometry.cpp:13: first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/eigenGeometry.dir/build.make:98: recipe for target 'eigenGeometry' failed
make[3]: *** [eigenGeometry] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/eigenGeometry.dir/all' failed
make[2]: *** [CMakeFiles/eigenGeometry.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/eigenGeometry.dir/rule' failed
make[1]: *** [CMakeFiles/eigenGeometry.dir/rule] Error 2
Makefile:118: recipe for target 'eigenGeometry' failed
make: *** [eigenGeometry] Error 2

错误提示如上，然后经过阅读个人认为是main函数重复定义，另外在cmakelist中直接将两个文件都生成了可执行文件，冲突了，修改cmakelist或者修改任意一个main函数的文件名可以解决该问题，但是本人刚刚开始学习，所以不敢肯定，恳求大佬指点

**Comment by LongruiDong** [comment]
> ====================[ Build | eigenGeometry | Debug ]===========================
> /snap/clion/82/bin/cmake/linux/bin/cmake --build /home/xhyu/slambook2/ch3/useGeometry/cmake-build-debug --target eigenGeometry -- -j 6
> Scanning dependencies of target eigenGeometry
> [ 33%] Building CXX object CMakeFiles/eigenGeometry.dir/home/xhyu/slambook2/ch3/examples/coordinateTransform.cpp.o
> [ 66%] Linking CXX executable eigenGeometry
> CMakeFiles/eigenGeometry.dir/home/xhyu/slambook2/ch3/examples/coordinateTransform.cpp.o: In function `main': /usr/include/eigen3/Eigen/src/Core/IO.h:129: multiple definition of `main'
> CMakeFiles/eigenGeometry.dir/eigenGeometry.cpp.o:/home/xhyu/slambook2/ch3/useGeometry/eigenGeometry.cpp:13: first defined here
> collect2: error: ld returned 1 exit status
> CMakeFiles/eigenGeometry.dir/build.make:98: recipe for target 'eigenGeometry' failed
> make[3]: *** [eigenGeometry] Error 1
> CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/eigenGeometry.dir/all' failed
> make[2]: *** [CMakeFiles/eigenGeometry.dir/all] Error 2
> CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/eigenGeometry.dir/rule' failed
> make[1]: *** [CMakeFiles/eigenGeometry.dir/rule] Error 2
> Makefile:118: recipe for target 'eigenGeometry' failed
> make: *** [eigenGeometry] Error 2
> 
> 错误提示如上，然后经过阅读个人认为是main函数重复定义，另外在cmakelist中直接将两个文件都生成了可执行文件，冲突了，修改cmakelist或者修改任意一个main函数的文件名可以解决该问题，但是本人刚刚开始学习，所以不敢肯定，恳求大佬指点

我也是改了cmakelists ，。。

**Comment by ten1er** [comment]
> > ====================[ Build | eigenGeometry | Debug ]===========================
> > /snap/clion/82/bin/cmake/linux/bin/cmake --build /home/xhyu/slambook2/ch3/useGeometry/cmake-build-debug --target eigenGeometry -- -j 6
> > Scanning dependencies of target eigenGeometry
> > [ 33%] Building CXX object CMakeFiles/eigenGeometry.dir/home/xhyu/slambook2/ch3/examples/coordinateTransform.cpp.o
> > [ 66%] Linking CXX executable eigenGeometry
> > CMakeFiles/eigenGeometry.dir/home/xhyu/slambook2/ch3/examples/coordinateTransform.cpp.o: In function `main': /usr/include/eigen3/Eigen/src/Core/IO.h:129: multiple definition of `main'
> > CMakeFiles/eigenGeometry.dir/eigenGeometry.cpp.o:/home/xhyu/slambook2/ch3/useGeometry/eigenGeometry.cpp:13: first defined here
> > collect2: error: ld returned 1 exit status
> > CMakeFiles/eigenGeometry.dir/build.make:98: recipe for target 'eigenGeometry' failed
> > make[3]: *** [eigenGeometry] Error 1
> > CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/eigenGeometry.dir/all' failed
> > make[2]: *** [CMakeFiles/eigenGeometry.dir/all] Error 2
> > CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/eigenGeometry.dir/rule' failed
> > make[1]: *** [CMakeFiles/eigenGeometry.dir/rule] Error 2
> > Makefile:118: recipe for target 'eigenGeometry' failed
> > make: *** [eigenGeometry] Error 2
> > 错误提示如上，然后经过阅读个人认为是main函数重复定义，另外在cmakelist中直接将两个文件都生成了可执行文件，冲突了，修改cmakelist或者修改任意一个main函数的文件名可以解决该问题，但是本人刚刚开始学习，所以不敢肯定，恳求大佬指点
> 
> 我也是改了cmakelists ，。。

/home/heyu/code/learngit/slambook2-master/ch3/build> make -j4
[ 18%] Built target eigenMatrix
[ 27%] Linking CXX executable eigenGeometry
[ 45%] Built target visualizeGeometry
[ 63%] Built target coordinateTransform
[ 81%] Built target plotTrajectory
CMakeFiles/eigenGeometry.dir/__/examples/coordinateTransform.cpp.o: In function `main':
/usr/include/eigen3/Eigen/src/Core/IO.h:129: multiple definition of `main'
CMakeFiles/eigenGeometry.dir/eigenGeometry.cpp.o:/home/heyu/code/learngit/slambook2-master/ch3/useGeometry/eigenGeometry.cpp:13: first defined here
collect2: error: ld returned 1 exit status
useGeometry/CMakeFiles/eigenGeometry.dir/build.make:120: recipe for target 'useGeometry/eigenGeometry' failed
make[2]: *** [useGeometry/eigenGeometry] Error 1
CMakeFiles/Makefile2:140: recipe for target 'useGeometry/CMakeFiles/eigenGeometry.dir/all' failed
make[1]: *** [useGeometry/CMakeFiles/eigenGeometry.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
*** Failure: Exit code 2 ***

遇到几乎一样的问题，请教一下大佬怎么改cmakelists?

**Comment by ten1er** [comment]
在useGeometry的CMakeLists.txt中将：
add_executable( eigenGeometry eigenGeometry.cpp ../examples/coordinateTransform.cpp)
改为：
add_executable( eigenGeometry eigenGeometry.cpp )
解决了我的问题。

**Comment by gaoxiang12** [comment]
已修复，应该是IDE自动加了一句不该加的executable。
