### ISSUE TITLE
ch7 pose_estimation_3d2d 链接阶段出现报错

### ISSUE THREAD

**Issue by ZoranDai** [gaoxiang12/slambook2#168]
高翔老师好，在make阶段出现了问题，希望能够得到一些您的帮助 谢谢！
[ 16%] Linking CXX executable pose_estimation_3d2d
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o: in function `unsigned long long fmt::v7::detail::width_checker<fmt::v7::detail::error_handler>::operator()<float, 0>(float) [clone .isra.0]':
pose_estimation_3d2d.cpp:(.text+0xe): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o: in function `unsigned long long fmt::v7::detail::precision_checker<fmt::v7::detail::error_handler>::operator()<float, 0>(float) [clone .isra.0]':
pose_estimation_3d2d.cpp:(.text+0x2e): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o: in function `Sophus::SO3Base<Sophus::SO3<double, 0> >::normalize() [clone .part.0]':
pose_estimation_3d2d.cpp:(.text+0xb4): undefined reference to `fmt::v7::vprint(fmt::v7::basic_string_view<char>, fmt::v7::basic_format_args<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text+0xd3): undefined reference to `fmt::v7::vprint(fmt::v7::basic_string_view<char>, fmt::v7::basic_format_args<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >)'
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o: in function `bundleAdjustmentGaussNewton(std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::aligned_allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > > const&, std::vector<Eigen::Matrix<double, 2, 1, 0, 2, 1>, Eigen::aligned_allocator<Eigen::Matrix<double, 2, 1, 0, 2, 1> > > const&, cv::Mat const&, Sophus::SE3<double, 0>&)':
pose_estimation_3d2d.cpp:(.text+0x3578): undefined reference to `fmt::v7::vprint(fmt::v7::basic_string_view<char>, fmt::v7::basic_format_args<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text+0x359a): undefined reference to `fmt::v7::vprint(fmt::v7::basic_string_view<char>, fmt::v7::basic_format_args<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >)'
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o: in function `Sophus::SE3<double, 0>::exp(Eigen::Matrix<double, 6, 1, 0, 6, 1> const&)':
pose_estimation_3d2d.cpp:(.text._ZN6Sophus3SE3IdLi0EE3expERKN5Eigen6MatrixIdLi6ELi1ELi0ELi6ELi1EEE[_ZN6Sophus3SE3IdLi0EE3expERKN5Eigen6MatrixIdLi6ELi1ELi0ELi6ELi1EEE]+0x833): undefined reference to `fmt::v7::vprint(fmt::v7::basic_string_view<char>, fmt::v7::basic_format_args<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >)'
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o:pose_estimation_3d2d.cpp:(.text._ZN6Sophus3SE3IdLi0EE3expERKN5Eigen6MatrixIdLi6ELi1ELi0ELi6ELi1EEE[_ZN6Sophus3SE3IdLi0EE3expERKN5Eigen6MatrixIdLi6ELi1ELi0ELi6ELi1EEE]+0x855): more undefined references to `fmt::v7::vprint(fmt::v7::basic_string_view<char>, fmt::v7::basic_format_args<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >)' follow
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o: in function `decltype (({parm#1}.begin)()) fmt::v7::formatter<fmt::v7::basic_string_view<char>, char, void>::parse<fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler> >(fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler>&)':
pose_estimation_3d2d.cpp:(.text._ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_[_ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_]+0x43b): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_[_ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_]+0x453): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_[_ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_]+0x4e6): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_[_ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_]+0x689): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_[_ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_]+0x698): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o:pose_estimation_3d2d.cpp:(.text._ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_[_ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_]+0x6a7): more undefined references to `fmt::v7::detail::error_handler::on_error(char const*)' follow
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o: in function `decltype (({parm#1}.begin)()) fmt::v7::formatter<fmt::v7::basic_string_view<char>, char, void>::parse<fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler> >(fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler>&)':
pose_estimation_3d2d.cpp:(.text._ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_[_ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_]+0x6e8): undefined reference to `fmt::v7::format_error::~format_error()'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_[_ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_]+0x6ef): undefined reference to `vtable for fmt::v7::format_error'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_[_ZN3fmt2v79formatterINS0_17basic_string_viewIcEEcvE5parseINS0_26basic_format_parse_contextIcNS0_6detail13error_handlerEEEEEDTcldtfp_5beginEERT_]+0x6f6): undefined reference to `typeinfo for fmt::v7::format_error'
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o: in function `fmt::v7::detail::buffer_appender<char> fmt::v7::detail::write<fmt::v7::detail::buffer_appender<char>, char, char>(fmt::v7::detail::buffer_appender<char>, fmt::v7::basic_string_view<char>, fmt::v7::basic_format_specs<char> const&)':
pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5writeINS1_15buffer_appenderIcEEccEET_S5_NS0_17basic_string_viewIT0_EERKNS0_18basic_format_specsIT1_EE[_ZN3fmt2v76detail5writeINS1_15buffer_appenderIcEEccEET_S5_NS0_17basic_string_viewIT0_EERKNS0_18basic_format_specsIT1_EE]+0x6d): undefined reference to `fmt::v7::detail::basic_data<void>::left_padding_shifts'
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o: in function `void fmt::v7::detail::value<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >::format_custom_arg<Eigen::Transpose<Eigen::Matrix<double, 3, 1, 0, 3, 1> const>, fmt::v7::detail::fallback_formatter<Eigen::Transpose<Eigen::Matrix<double, 3, 1, 0, 3, 1> const>, char, void> >(void const*, fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler>&, fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>&)':
pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0x1f3): undefined reference to `std::locale fmt::v7::detail::locale_ref::get<std::locale>() const'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0xa41): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0xa69): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0xaf4): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0xb0d): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0xb36): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o:pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeIKNS9_6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEENS1_18fallback_formatterISE_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0xb6c): more undefined references to `fmt::v7::detail::error_handler::on_error(char const*)' follow
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o: in function `void fmt::v7::detail::value<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >::format_custom_arg<Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> >, fmt::v7::detail::fallback_formatter<Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> >, char, void> >(void const*, fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler>&, fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>&)':
pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0x1f3): undefined reference to `std::locale fmt::v7::detail::locale_ref::get<std::locale>() const'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0xa41): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0xa69): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0xaf4): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0xb0d): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0xb36): undefined reference to `fmt::v7::detail::error_handler::on_error(char const*)'
/usr/bin/ld: CMakeFiles/pose_estimation_3d2d.dir/pose_estimation_3d2d.cpp.o:pose_estimation_3d2d.cpp:(.text._ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_[_ZN3fmt2v76detail5valueINS0_20basic_format_contextINS1_15buffer_appenderIcEEcEEE17format_custom_argIN5Eigen9TransposeINS9_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEENS1_18fallback_formatterISD_cvEEEEvPKvRNS0_26basic_format_parse_contextIcNS1_13error_handlerEEERS6_]+0xb6c): more undefined references to `fmt::v7::detail::error_handler::on_error(char const*)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/pose_estimation_3d2d.dir/build.make:102：pose_estimation_3d2d] 错误 1
make[1]: *** [CMakeFiles/Makefile2:86：CMakeFiles/pose_estimation_3d2d.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2

**Comment by gaoxiang12** [comment]
OpenCV 4.3以上应该要额外连接fmt库。在CMakeLists.txt里的target_link_libraries里加一个fmt试试？

**Comment by ZoranDai** [comment]
好的 谢谢高翔老师 target_link_libraries后面加了fmt::fmt后重新编译 问题解决了！
