### ISSUE TITLE
ch7 3d3d程序运行不对

### ISSUE THREAD

**Issue by kevinqyh** [gaoxiang12/slambook2#17]
calling bundle adjustment
iteration= 0	 chi2= 1.815772	 time= 2.3413e-05	 cumTime= 2.3413e-05	 edges= 75	 schur= 0	 lambda= 0.000787	 levenbergIter= 1
iteration= 1	 chi2= 1.815193	 time= 1.2752e-05	 cumTime= 3.6165e-05	 edges= 75	 schur= 0	 lambda= 0.000524	 levenbergIter= 1
iteration= 2	 chi2= 1.815193	 time= 1.0919e-05	 cumTime= 4.7084e-05	 edges= 75	 schur= 0	 lambda= 0.000350	 levenbergIter= 1
iteration= 3	 chi2= 1.815193	 time= 1.0669e-05	 cumTime= 5.7753e-05	 edges= 75	 schur= 0	 lambda= 0.000233	 levenbergIter= 1
iteration= 4	 chi2= 1.815193	 time= 1.0468e-05	 cumTime= 6.8221e-05	 edges= 75	 schur= 0	 lambda= 0.000155	 levenbergIter= 1
iteration= 5	 chi2= 1.815193	 time= 1.0481e-05	 cumTime= 7.8702e-05	 edges= 75	 schur= 0	 lambda= 0.000104	 levenbergIter= 1
iteration= 6	 chi2= 1.815193	 time= 2.1083e-05	 cumTime= 9.9785e-05	 edges= 75	 schur= 0	 lambda= 0.070714	 levenbergIter= 5
iteration= 7	 chi2= 1.815193	 time= 1.112e-05	 cumTime= 0.000110905	 edges= 75	 schur= 0	 lambda= 0.047143	 levenbergIter= 1
iteration= 8	 chi2= 1.815193	 time= 2.3951e-05	 cumTime= 0.000134856	 edges= 75	 schur= 0	 lambda= 12654823.401608	 levenbergIter= 7
optimization costs time: 0.00041749 seconds.

after optimization:
T=
   0.997207   0.0583427   -0.046639    0.137988
 -0.0578775     0.99826   0.0112663   -0.065517
  0.0472151 -0.00853546    0.998848  -0.0298169
          0           0           0           1
double free or corruption (out)
已放弃 (核心已转储)

不太明白为啥运行失败
单独下载了第一版第七章代码，发现可以运行成功
有个疑问是 为啥第一版的代码里面 jacobian的顺序把单位阵放后面了?按照SE(3)扰动模型不是应该在前面吗？

**Comment by gaoxiang12** [comment]
double free原因应该是gcc -march=native与g2o不兼容，去掉之后可以编译运行。
已在https://github.com/gaoxiang12/slambook2/commit/7f58f5e7de8d8dc1dfa81475f5289f05ef70ae05 中修复。
