### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by iamkrs9** [gaoxiang12/slambook2#175]
This is not an issue with the code but rather a question about mapping. Could you please point me to any sources with the help of which I can try to build a mapping program that would track and build something like an occupancy grid map of the path that the robot takes?

**Comment by gaoxiang12** [comment]
Hi @iamkrs9 this depends on what kind of map you want to build and which sensors you have. If you mean using 2D or 3D lidar to build occupancy grids, I suggest trying [Cartographer](https://github.com/cartographer-project/cartographer) as the first step. Or if you want some point cloud maps from camera images, I think the open-source list in the last chapter of [slambook](https://github.com/gaoxiang12/slambook-en) may help you.

**Comment by iamkrs9** [comment]
Thanks @gaoxiang12
