### ISSUE TITLE
ch12 关于对极约束的一个问题

### ISSUE THREAD

**Issue by ynma-hanvo** [gaoxiang12/slambook2#187]
bool epipolarSearch(
    const Mat &ref, const Mat &curr,
    const SE3d &T_C_R, const Vector2d &pt_ref,
    const double &depth_mu, const double &depth_cov,
    Vector2d &pt_curr, Vector2d &epipolar_direction) {
    Vector3d f_ref = px2cam(pt_ref);
    f_ref.normalize(); //为啥?
    Vector3d P_ref = f_ref * depth_mu;    // 参考帧的 P 向量
...........
}

请问 为什么 px2cam(pt_ref); 的结果要normalize,   这个结果应该是归一化平面的点坐标了， 
后面直接乘深度 就是相机坐标下的点坐标了，

**Comment by ynma-hanvo** [comment]
> 楼主你知道为什么吗？谢谢
这个地方应该用的是单位向量，( 最后还是转换为齐次坐标，应该没啥区别)

**Comment by SelfStudyM** [comment]
个人认为：

Vector3d f_ref = px2cam(pt_ref);
这一步得到的是一个从光心（optical center）指向参考点在归一化平面上投影的一个向量。即图12-4 或 图12-2（第二版第12章）中的 O1p1 向量。

参考点, P, 将会出现在这个向量所指向的方向上面。但这个向量，f_ref，到这一步为止本身并不是一个单位方向向量。

通过：
f_ref.normalize(); 
我们把， f_ref， 转化为了一个单位向量，这个单位向量的方向是从光心出发指向参考点所在的位置的一条射线。

所以：
Vector3d P_ref = f_ref * depth_mu;
中的 P_ref， 就是一个从光心出发到参考点的（估测，estimaed）向量，即即图12-4 中 O1P。其中 depth_mu 是我们预估深度正态分布的均值（同时也是众数值，mode）。

其实书中原文也有说明： “这里说的深度值是O1P的长度，它和我们在针孔相机模型的提到的‘深度’有少许不同” （the depth value mentioned here is the length of O1P, which is slightly different from the depth we mentioned in the pinhole camera model）。

所以 normalize() 的原因就是把该向量，f_ref，转化为一个单位方向向量。单位方向向量乘以向量长度则得到连接光心与参考点的（估测）向量。
