### ISSUE TITLE
When will book version 2 be released?

### ISSUE THREAD

**Issue by kentsyx** [gaoxiang12/slambook2#2]
Hello Dr. Gao, 

Thank you for bringing vSLAM accessible to a variety of audience. I'm wondering when the second version draft will be released? Can't wait to read it!

**Comment by gaoxiang12** [comment]
Hi @kentsyx , I still have 2 chapters to do for now, including an engineering chapter. I think 8 weeks would be a reasonable time for me. Thanks for attention!

**Comment by kentsyx** [comment]
Got it, thanks!
