### ISSUE TITLE
Image pyramid calculation without gaussian blur

### ISSUE THREAD

**Issue by xmba15** [gaoxiang12/slambook2#204]
Hi @gaoxiang12 Thank you for this great learning source.
I just want to raise a small question about the image pyramid calculation you used in chapter 8 (optical flow estimation, direct pose estimation)

here in the code, we only have a downsampling processing.
https://github.com/gaoxiang12/slambook2/blob/master/ch8/optical_flow.cpp#L309

but in the definition of [image pyramid](https://en.wikipedia.org/wiki/Pyramid_(image_processing)#/media/File:Image_pyramid.svg), I think a gaussian blur is added before downsampling to reduce aliasing.

Not a big deal though but maybe it can be added to a newer version of slambook.

**Comment by gaoxiang12** [comment]
Thanks for pointing it out. Actually, as I know the Gaussian blur is an optional step in vslam. Some implementations like SVO and DSO do not have the Gaussian blur step and feature-based vslam like ORB-SLAM normally has this. I'll think of adding a short text introduction in the current version. Thanks.

**Comment by xmba15** [comment]
Thanks. I am looking forward to it.
I will close this issue then.
