### ISSUE TITLE
ch3 poltTrajectory 运行出现错误

### ISSUE THREAD

**Issue by weiwanhui** [gaoxiang12/slambook2#21]
cannot find trajectory file at ./trajectory.txt
是不是
string trajectory_file = "./trajectory.txt";
这句的问题？怎么修改呢？

**Comment by Frozenheart1998** [comment]
你是不是把trajectory.txt放在/build的上层文件夹里了。试试看"../trajectory"行不行

**Comment by weiwanhui** [comment]
是的是的，问了个蠢问题。。谢谢谢谢，我是把txt又复制到build文件了一次，就可以了。
