### ISSUE TITLE
CH06中g2oCurveFitting运行出现错误

### ISSUE THREAD

**Issue by yaonuliya** [gaoxiang12/slambook2#212]
/usr/local/include/g2o/core/base_fixed_sized_edge.hpp:166:3: error: ‘FixedArray {aka class ceres::internal::FixedArray<double, 9l>}’ has no member named ‘fill’
   add_vertex.fill(0.);
   ^
/usr/local/include/g2o/core/base_fixed_sized_edge.hpp:173:5: error: ‘FixedArray {aka class ceres::internal::FixedArray<double, 9l>}’ has no member named ‘data’
     vertex->oplus(add_vertex.data());
     ^
/usr/local/include/g2o/core/base_fixed_sized_edge.hpp:179:5: error: ‘FixedArray {aka class ceres::internal::FixedArray<double, 9l>}’ has no member named ‘data’
     vertex->oplus(add_vertex.data());
     ^
/usr/local/include/g2o/core/base_fixed_sized_edge.hpp: In instantiation of ‘void g2o::BaseFixedSizedEdge<D, E, VertexTypes>::linearizeOplusN() [with int N = 1; int D = 2; E = Eigen::Matrix<double, 2, 1>; VertexTypes = {VertexPoseAndIntrinsics, VertexPoint}]’:
/usr/local/include/g2o/core/base_fixed_sized_edge.hpp:192:41:   required from ‘void g2o::BaseFixedSizedEdge<D, E, VertexTypes>::linearizeOplusNs(std::index_sequence<Ints ...>) [with long unsigned int ...Ints = {0ul, 1ul}; int D = 2; E = Eigen::Matrix<double, 2, 1>; VertexTypes = {VertexPoseAndIntrinsics, VertexPoint}; std::index_sequence<Ints ...> = std::integer_sequence<long unsigned int, 0ul, 1ul>]’
/usr/local/include/g2o/core/base_fixed_sized_edge.hpp:200:19:   required from ‘void g2o::BaseFixedSizedEdge<D, E, VertexTypes>::linearizeOplus() [with int D = 2; E = Eigen::Matrix<double, 2, 1>; VertexTypes = {VertexPoseAndIntrinsics, VertexPoint}]’
/home/lw/projects/slam/ch9/bundle_adjustment_g2o/bundle_adjustment_g2o.cpp:202:1:   required from here
/usr/local/include/g2o/core/base_fixed_sized_edge.hpp:166:3: error: ‘FixedArray {aka class ceres::internal::FixedArray<double, 3l>}’ has no member named ‘fill’
   add_vertex.fill(0.);
   ^
/usr/local/include/g2o/core/base_fixed_sized_edge.hpp:173:5: error: ‘FixedArray {aka class ceres::internal::FixedArray<double, 3l>}’ has no member named ‘data’
     vertex->oplus(add_vertex.data());
     ^
/usr/local/include/g2o/core/base_fixed_sized_edge.hpp:179:5: error: ‘FixedArray {aka class ceres::internal::FixedArray<double, 3l>}’ has no member named ‘data’
     vertex->oplus(add_vertex.data());
     ^
CMakeFiles/bundle_adjustment_g2o.dir/build.make:62: recipe for target 'CMakeFiles/bundle_adjustment_g2o.dir/bundle_adjustment_g2o.cpp.o' failed
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/bundle_adjustment_g2o.dir/all' failed
Makefile:83: recipe for target 'all' failed
make[2]: *** [CMakeFiles/bundle_adjustment_g2o.dir/bundle_adjustment_g2o.cpp.o] Error 1
make[1]: *** [CMakeFiles/bundle_adjustment_g2o.dir/all] Error 2
make: *** [all] Error 2
*** 失败：退出代码 2 ***

出现上述问题，可能是ceres版本问题，但是重新安装之后仍然无法解决。特此来寻求大佬帮助，有没有遇到相同情况的伙伴，你们是如何解决的呢？

**Comment by yaonuliya** [comment]
ok,感谢回复，这个问题已经解决了。

**Comment by haohaoalt** [comment]
git clone https://github.com/RainerKuemmerle/g2o   # 克隆最新版本g2o
cd g2o
git checkout **9b41a4e**

**Comment by haohaoalt** [comment]
git clone https://github.com/RainerKuemmerle/g2o   # 克隆最新版本g2o
cd g2o
git checkout **9b41a4e**
