### ISSUE TITLE
ch9的Ceres BA疑问

### ISSUE THREAD

**Issue by yg1031** [gaoxiang12/slambook2#214]
ch9中的例程，bundle_adjustment_ceres.cpp中，
采用的数据为problem-16-22106-pre.txt，其中包括16个相机，应该是同一个相机吧，
那么对这些相机的9维参数进行优化，如何保证优化后各相机的内参相同呢？

**Comment by yg1031** [comment]
优化后的各相机内参好像是不同的。
[6] focal length, [7-8] second and forth order radial distortion
![QQ截图20211217172043](https://user-images.githubusercontent.com/32894843/146521059-09b395b3-982f-42fc-9779-d44cf6a7fbbf.jpg)

**Comment by stu-fullstack** [comment]
16个相机是不一样的相机，记得那个数据集是 SFM 里的，就是用多视角的图像进行三维重建。
