### ISSUE TITLE
ch5 joinMap.cpp

### ISSUE THREAD

**Issue by MF-Ahmed** [gaoxiang12/slambook2#245]
make                                                                                                                         rgbd/build main
You are using Ubuntu 20.04, fmt::fmt will be linked
-- Configuring done
-- Generating done
-- Build files have been written to: /home/uzi/Data/AllGit/SLAMBook2_Codes/ch5/rgbd/build
Consolidate compiler generated dependencies of target joinMap
[ 50%] Building CXX object CMakeFiles/joinMap.dir/joinMap.cpp.o
In file included from /usr/local/include/fmt/format.h:48,
                 from /usr/local/include/sophus/common.hpp:35,
                 from /usr/local/include/sophus/types.hpp:7,
                 from /usr/local/include/sophus/rotation_matrix.hpp:9,
                 from /usr/local/include/sophus/so3.hpp:6,
                 from /usr/local/include/sophus/se3.hpp:6,
                 from /home/uzi/Data/AllGit/SLAMBook2_Codes/ch5/rgbd/joinMap.cpp:6:
/usr/local/include/fmt/core.h: In instantiation of ‘constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_value(T&&) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; T = Eigen::Transpose<Eigen::Matrix<double, 4, 1> >&]’:
/usr/local/include/fmt/core.h:1776:29:   required from ‘void fmt::v9::print(fmt::v9::format_string<T ...>, T&& ...) [with T = {Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> >}; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> > >]’
/usr/local/include/sophus/so3.hpp:320:5:   required from ‘void Sophus::SO3Base<Derived>::normalize() [with Derived = Sophus::SO3<double>]’
/usr/local/include/sophus/so3.hpp:532:20:   required from ‘Sophus::SO3<Scalar_, Options>::SO3(const Eigen::QuaternionBase<OtherDerived>&) [with D = Eigen::Quaternion<double>; Scalar_ = double; int Options = 0]’
/usr/local/include/sophus/se3.hpp:507:51:   required from ‘Sophus::SE3<Scalar_, Options>::SE3(const Eigen::Quaternion<_Scalar>&, const Point&) [with Scalar_ = double; int Options = 0; Sophus::SE3<Scalar_, Options>::Point = Eigen::Matrix<double, 3, 1>]’
/home/uzi/Data/AllGit/SLAMBook2_Codes/ch5/rgbd/joinMap.cpp:36:69:   required from here
/usr/local/include/fmt/core.h:3290:44:   in ‘constexpr’ expansion of ‘fmt::v9::make_format_args<>((* & args#0))’
/usr/local/include/fmt/core.h:3290:15:   in ‘constexpr’ expansion of ‘fmt::v9::format_arg_store<fmt::v9::basic_format_context<fmt::v9::appender, char>, Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> > >((* & args#0))’
/usr/local/include/fmt/core.h:1900:77:   in ‘constexpr’ expansion of ‘fmt::v9::detail::make_arg<true, fmt::v9::basic_format_context<fmt::v9::appender, char>, fmt::v9::detail::type::custom_type, Eigen::Transpose<Eigen::Matrix<double, 4, 1> >&>((* & args#0))’
/usr/local/include/fmt/core.h:1756:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1756 |       formattable,
      |       ^~~~~~~~~~~
make[2]: *** [CMakeFiles/joinMap.dir/build.make:76: CMakeFiles/joinMap.dir/joinMap.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/joinMap.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by JuexiaOfficial** [comment]
how to solve it?
