### ISSUE TITLE
关于Ch6 123页 最小二乘公式引出的疑问

### ISSUE THREAD

**Issue by YangGangZhiQi** [gaoxiang12/slambook2#267]
高博好，非常感谢您的工作贡献。最近看这本书时，对 6.1.2 “最小二乘的引出“这开始两节的最开始两个公式有个疑问。
![最小二乘引出公式](https://user-images.githubusercontent.com/87355944/212459983-0f7227f6-3dfe-45a1-a5e6-8cf3f62a83d3.png)
书中说假设噪声项Vk服从高斯分布，推出观测数据的条件概率也服从高斯分布。我不明白为什么能这么推导。按照我的理解，这里只有h(yj，xk)也服从高斯分布才能做出上述推导。可是h(yj，xk)不一定服从高斯分布吧。希望能得到解答，谢谢。

**Comment by gaoxiang12** [comment]
你好，该式是说，把y_j和x_k的真值（注意是数值）代入h函数就能得到一个数值，即为z。不受噪声影响时，z精确地等于该数据。受高斯噪声影响时，z的均值等于该数值，但有一个方差为Q的不确定度。

**Comment by YangGangZhiQi** [comment]
谢谢高博的解答，我理解了。 刚刚接触视觉SLAM，您的书对我帮助很大，感谢。
