### ISSUE TITLE
公式6.41

### ISSUE THREAD

**Issue by LiamLYJ** [gaoxiang12/slambook2#27]
请问公式6.41中的$\sigma$这一项是为什么？

**Comment by gaoxiang12** [comment]
\sigma平方是噪声的协方差，即式6.13中间的那个协方差矩阵。

**Comment by LiamLYJ** [comment]
@gaoxiang12 请问6.41是不是从6.32中推导出的？ 但6.32中没有\sigma项。。6.41中的两边的\sigma不是也可以约去吗？

**Comment by gaoxiang12** [comment]
是这样的：完整的状态估计要带上协方差矩阵，要从原始的最大似然估计出发。而6.32那部分内容，考虑到读者第一次接触到非线性优化，就略去了协方差矩阵。
6.41那个例子比较简单，所有的数据都使用同一种噪声，并且还是标量的，所以看上去可以约掉。但实际情况多数是矢量的误差，噪声来源也可能不一样，所以通常的写法是不约掉的。

**Comment by LiamLYJ** [comment]
@gaoxiang12 Thx ~!
