### ISSUE TITLE
float dd = d / 5000;

### ISSUE THREAD

**Issue by xhniu** [gaoxiang12/slambook2#28]
float dd = d / 5000;
            Point2d p1 = pixel2cam(Point2f(image_points.at<double>(i, 0), image_points.at<double>(i, 1)), K);
why use dd = d / 5000? how to get this parameter?

**Comment by gaoxiang12** [comment]
This is because the depth map use 5000 as its depth unit, so that a depth value 5000 means 1 meter in real world. 
Normally Kinect v1 and v2 set this unit as 1000, but there are also sensors using different scale units.
