### ISSUE TITLE
请问Ubuntu版本有没有要求

### ISSUE THREAD

**Issue by hanmmmmm** [gaoxiang12/slambook2#293]
想问一下这个项目的编译和运行对Ubuntu版本有没有什么要求？  ubuntu22能不能顺利学完所有内容？ 
谢谢！

**Comment by gaoxiang12** [comment]
这个项目对ubuntu版本依赖没那么强烈，主要是不需要ros，应该可以编，有问题可以提issue。

**Comment by hanmmmmm** [comment]
好的，感谢
