### ISSUE TITLE
The dataset normalization function in ch9

### ISSUE THREAD

**Issue by zhutmost** [gaoxiang12/slambook2#30]
您好，
请问能解释下第9章的代码中，`common.cpp`和`rotation.h`下面的几个函数么，即它们都做了什么事，以及关键变量的含义？
1. AngleAxisRotationPoint。
2. Camera 和 Angle-Axis & Center的相互转换中，Center指的是什么？

**Comment by gaoxiang12** [comment]
AngleAxisRotationPoint是使用角轴对点进行坐标变换。
Camera Center是相机中心点的世界坐标。

**Comment by zhutmost** [comment]
感谢，我已经看明白了。
