### ISSUE TITLE
ch8 opencv 3.2.0 parallel_for_ doesn't support std::bind function

### ISSUE THREAD

**Issue by rancheng** [gaoxiang12/slambook2#32]
compiling error looks like this:

```cpp
/home/ran/Documents/Playground/slambook2/ch8/direct_method.cpp: In function ‘void DirectPoseEstimationSingleLayer(const cv::Mat&, const cv::Mat&, const VecVector2d&, std::vector<double, std::allocator<double> >, Sophus::SE3d&)’:
/home/ran/Documents/Playground/slambook2/ch8/direct_method.cpp:172:36: error: invalid initialization of reference of type ‘const cv::ParallelLoopBody&’ from expression of type ‘std::_Bind_helper<false, void (JacobianAccumulator::*)(const cv::Range&), JacobianAccumulator*, const std::_Placeholder<1>&>::type {aka std::_Bind<void (JacobianAccumulator::*(JacobianAccumulator*, std::_Placeholder<1>))(const cv::Range&)>}’
                           std::bind(&JacobianAccumulator::accumulate_jacobian, &jaco_accu, std::placeholders::_1));
                           ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/opencv2/core.hpp:3216:0,
                 from /usr/include/opencv2/opencv.hpp:52,
                 from /home/ran/Documents/Playground/slambook2/ch8/direct_method.cpp:1:
/usr/include/opencv2/core/utility.hpp:478:17: note: in passing argument 2 of ‘void cv::parallel_for_(const cv::Range&, const cv::ParallelLoopBody&, double)’
 CV_EXPORTS void parallel_for_(const Range& range, const ParallelLoopBody& body, double nstripes=-1.);
```

go to opencv `utility.hpp` and found that the definition of `parallel_for_` is like this:

```cpp
CV_EXPORTS void parallel_for_(const Range& range, const ParallelLoopBody& body, double nstripes=-1.);
```

so, we have to modify the class `JacobianAccumulator`, extend it from `cv::ParallelLoopBody` and change `accumulate_jacobian` function to it's operator override: `virtual void operator()(const cv::Range& range) const`

I have updated the source in my folk, you can download from [here](https://github.com/rancheng/slambook2/blob/opencv3_2_0/ch8/direct_method.cpp)

**Comment by rancheng** [comment]
and if you are using CLion, please note that the source file's data reference was in current directory like this: 

```cpp
string left_file = "./left.png";
string disparity_file = "./disparity.png";
```

this is dirty, please make sure you parameterize your file path, since the executive file will be compiled in cmake-build-debug directory

**Comment by rancheng** [comment]
The experiments are conducted in 4 scales:
![1s](https://user-images.githubusercontent.com/2719771/67056620-d8c8e900-f11a-11e9-9713-f3c6db2a239e.png)
![2s](https://user-images.githubusercontent.com/2719771/67056622-da92ac80-f11a-11e9-86fd-b899f911cc5a.png)
![3s](https://user-images.githubusercontent.com/2719771/67056633-e0888d80-f11a-11e9-80b6-a3fb3aa5a9f5.png)
![4s](https://user-images.githubusercontent.com/2719771/67056637-e2525100-f11a-11e9-804b-ce8ad8573693.png)

**Comment by gaoxiang12** [comment]
Thanks for commit. Looks like since opencv 4 the parallel_for_ has an overloaded form that supports std::function as the second input param:  [here](https://docs.opencv.org/master/db/de0/group__core__utils.html#ga12a32916e3be6a87be3a4e8fbc799eec).
For the second comment, I agree with that using params or gflags would be more elegant, but it's ok to use simple global variables in small demos like this one.

**Comment by rancheng** [comment]
Thanks for your kind reply, I really appreciate your contributions!
Just ignore my jibber jabber on the second comment, yes, I compiled opencv4 and tested your code last night, that passed.
I'll close this issue, since the problem was solved, again, thanks for your great work on SLAMBOOK!
