### ISSUE TITLE
Ch3与Ch4两个例子中Quaterniond类型的初始化不一致

### ISSUE THREAD

**Issue by bill4u** [gaoxiang12/slambook2#33]
Ch3中plotTrajectory.cpp中第24行的Quaterniond的顺序是qw, qx, qy, qz，但是Ch4中trajectoryError.cpp中第51行，Quaterniond顺序是qx, qy, qz, qw。而实际Quaternion.h头文件中定义的顺序是Quaternion(const Scalar& w, const Scalar& x, const Scalar& y, const Scalar& z)

但是奇怪的是把Ch4中的qw的顺序来回调整，得出来的轨迹似乎是一样的？

**Comment by gaoxiang12** [comment]
感谢，应该是第4章构造有误。然而两条轨迹的旋转误差相对来说很小，导致看不出来而已。。
