### ISSUE TITLE
ch07/orb_self.cpp的代码笔误

### ISSUE THREAD

**Issue by bittergourd1224** [gaoxiang12/slambook2#36]
第375行中
`int idx_pq = i * 8 + k;`
是否应该为
`int idx_pq = i * 32 + k;`

另外问一下，代码中的ORB_pattern[256 * 4]是否就是选取的特征点附近随机像素？可是这里是人为输入的，是有其他特殊含义吗？
另外书中有个笔误，就不另开issue了。p68倒数第二行的Panglin少了一个o。

**Comment by Mingrui-Yu** [comment]
同认为应该是×32。

关于ORB_pattern，我觉得这个ORB_pattern就是随机生成的，但对每一次匹配用的都是同样的ORB_pattern（如果两幅图像中的同一特征点的ORB特征是用的不同的随机点，那肯定是没法匹配的），所以只需要在之前随机生成一次就可以了。代码中只是省略了随机生成的过程，直接给出表就是了。

**Comment by bittergourd1224** [comment]
@Mingrui-Yu 多谢解答。感觉还是在第一次使用前用随机数生成更直观一些，不过意义一样无所谓啦

**Comment by gaoxiang12** [comment]
感谢各位讨论，已修复 。

**Comment by bittergourd1224** [comment]
收到:smile:
