### ISSUE TITLE
ch12中dense_mapping.cpp中代码注释有误

### ISSUE THREAD

**Issue by WZG3661** [gaoxiang12/slambook2#37]
ch12的dense_mapping.cpp中的第390行代码
`//    [ f_cur^T f_ref, -f2^T f2    ] [d_cur] = [f2^T t   ]`
下面的代码跟这一行的公式没有对应起来，仔细一看才发现在这一行注释中，第一个中括号内的 f_cur应为f2，也就是下面这样
`//    [ f2^T f_ref, -f2^T f2    ] [d_cur] = [f2^T t   ]`
这样才对吧

**Comment by LarryDong** [comment]
是的，我看书时也发现了。正巧在一页最后，我盯着注释看了半天没看懂公式是在干啥，搜了一下确定错了再看后面代码，是对的……

**Comment by gaoxiang12** [comment]
感谢，已修复，各位看得真细致。

**Comment by mayingqi** [comment]
请问dense_mapping.cpp的测试数据在哪
