### ISSUE TITLE
CH6中的CMakeLists.txt文件中引用g2o的参数名有误

### ISSUE THREAD

**Issue by bill4u** [gaoxiang12/slambook2#38]
在MAC下编译，使用的FindG2O.cmake文件查找。但是CMakeLists.txt中这一句有问题，找不到值！include_directories(${G2O_INCLUDE_DIRS})
查看FindG2O.cmake发现应该改为：include_directories(${G2O_INCLUDE_DIR})

同时把target_link_libraries中的g2o_core和g2o_stuff修改为${G2O_CORE_LIBRARY} 和${G2O_STUFF_LIBRARY}

**Comment by gaoxiang12** [comment]
这个代码库只支持Ubuntu系列。
Mac上遇到任何问题请自行解决，如有整理意向请自行folk然后在你自己分支上修改。
