### ISSUE TITLE
Ch12中的camera fy 为什么是负值？

### ISSUE THREAD

**Issue by LiamLYJ** [gaoxiang12/slambook2#41]
请问： Ch12中的camera fy 为什么是负值？

**Comment by gaoxiang12** [comment]
因为这个数据集图像是Y轴倒过来的，所以fy取负值。

**Comment by LiamLYJ** [comment]
![image](https://user-images.githubusercontent.com/28727167/68913975-edd77d00-0797-11ea-87c1-9124933c86a1.png)
@gaoxiang12 公式13.15好像推错了

**Comment by gaoxiang12** [comment]
谢谢指出，该问题已归类至勘误表，请查看：https://github.com/gaoxiang12/slambook2/blob/master/errata.pdf
勘误表会定期提交给出版社，由出版社修改原稿后，在下一次印刷时修正。
