### ISSUE TITLE
高老師您好  我發現 github slambook2（也就是這個網址）上面下載的代碼的 3dparty裏面是空的  我自己下載的 lie group  lib ———sophus   I  can  camke and make ，but dont know how to write the CMakeList.txt

### ISSUE THREAD

**Issue by resplendent-star** [gaoxiang12/slambook2#44]

**Comment by bene-yan** [comment]
我下载后的3dparty也是空的，好像是里面那个google的库下载失败导致的。我把其它的库一个一个点进去下载的。

**Comment by gaoxiang12** [comment]
这可能是由于git clone时没有同步子模块造成的。
请试试在代码根目录下，使用git submodule init，然后git submodule update，就会更新三方库。

**Comment by resplendent-star** [comment]
> 这可能是由于git clone时没有同步子模块造成的。
> 请试试在代码根目录下，使用git submodule init，然后git submodule update，就会更新三方库。

請問高老師 ，代碼根目錄是哪個呢  是包括所有的“ch3 ch4 ..."的那個大的根目錄嗎
還是說在  3rdparty/g2o下面就是代碼根目錄

我使用git submodule init 得到的結果就是
---------------------------------------------------------------
lzw@lzw:~/learn_slam/bookcode2/3rdparty/g2o$ git submodule init
fatal: Not a git repository (or any of the parent directories): .git
lzw@lzw:~/learn_slam/bookcode2/3rdparty/g2o$ 

或者
---------------------------------------------------------------------------------
lzw@lzw:~/learn_slam/bookcode2$ git submodule init
fatal: Not a git repository (or any of the parent directories): .git
lzw@lzw:~/learn_slam/bookcode2$ 
都不太行，報錯

**Comment by resplendent-star** [comment]
我使用git submodule init 得到的結果就是
lzw@lzw:/learn_slam/bookcode2/3rdparty/g2o$ git submodule init
fatal: Not a git repository (or any of the parent directories): .git
lzw@lzw:/learn_slam/bookcode2/3rdparty/g2o$

或者
lzw@lzw:/learn_slam/bookcode2$ git submodule init
fatal: Not a git repository (or any of the parent directories): .git
lzw@lzw:/learn_slam/bookcode2$
都不太行，報錯

**Comment by resplendent-star** [comment]
> Hello, 你应该在slambook2下进行这个操作。

你好 高老師  我確實是在 slambook2下進行的這個操作  ，git submodule init  但是不行呀

**Comment by resplendent-star** [comment]
![2019-11-19 10-37-50屏幕截图](https://user-images.githubusercontent.com/41502003/69111636-21c4e200-0ab9-11ea-9973-87aa2176e23c.png)

**Comment by gaoxiang12** [comment]
ok，你应该使用git clone来下载代码。你现在是通过点github的下载按钮的，那只会下载代码文件本身，无法使用git的功能。而我们书里的三方库是通过git submodule功能管理的，所以你应该通过git clone来获取代码。

**Comment by resplendent-star** [comment]
> ok，你应该使用git clone来下载代码。你现在是通过点github的下载按钮的，那只会下载代码文件本身，无法使用git的功能。而我们书里的三方库是通过git submodule功能管理的，所以你应该通过git clone来获取代码。

好的谢谢高老师
