### ISSUE TITLE
ch8中direct_method编译没问题，运行的时候显示段错误，请问可能是什么原因?

### ISSUE THREAD

**Issue by vo8zhaoyao** [gaoxiang12/slambook2#46]

**Comment by gaoxiang12** [comment]
请描述现象或给出报错结果，方便别人帮你分析原因。
如果什么信息都没有，请用gdb或其他工具自行调试。

**Comment by vo8zhaoyao** [comment]
高博您好，感谢您的回复，我运行时的报错结果如下，应该属于什么信息也没有
xlab@xlab:~/slambook2/ch8/build$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xlab/slambook2/ch8/build
xlab@xlab:~/slambook2/ch8/build$ make
[ 50%] Built target direct_method
[100%] Built target optical_flow
xlab@xlab:~/slambook2/ch8/build$ ./direct_method 
段错误 (核心已转储)

**Comment by vo8zhaoyao** [comment]
高博您好，感谢您的回复，我运行段结果如下，应该属于什么信息也没有，可能我需要自己找原因，很困惑。
xlab@xlab:~/slambook2/ch8/build$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xlab/slambook2/ch8/build
xlab@xlab:~/slambook2/ch8/build$ make
[ 50%] Built target direct_method
[100%] Built target optical_flow
xlab@xlab:~/slambook2/ch8/build$ ./direct_method 
段错误 (核心已转储)

**Comment by gaoxiang12** [comment]
如果你有IDE，可以使用IDE里的断点调试功能。没有的话，用gdb命令也行，不过使用方法需要自学一下。
我推测应该是目录不对或者找不到文件一类的问题。

**Comment by vo8zhaoyao** [comment]
十分感谢，我已经找到了问题所在，是图片路径的问题，我将例程里的相对路径改为绝对路径之后就可以了！
// paths
string left_file = "/home/xlab/slambook2/ch8/left.png";
string disparity_file = "/home/xlab/slambook2/ch8/disparity.png";
boost::format fmt_others("/home/xlab/slambook2/ch8/%06d.png");    // other files
