### ISSUE TITLE
Questions about ch13

### ISSUE THREAD

**Issue by TongLing916** [gaoxiang12/slambook2#5]
Hello, I have looked over the source code of the project in `ch13` and have two questions:

1) First question is about the [calculation of baseline](https://github.com/gaoxiang12/slambook2/blob/master/ch13/src/dataset.cpp#L40). Why is`t.sqauredNorm()` used to calculate the baseline instead of `t.norm()`?

2) Second question is about [Map::InsertKeyFrame()](https://github.com/gaoxiang12/slambook2/blob/master/ch13/src/map.cpp#L27). Why check if `frame_id_` exists when `keyframes_` actually contains `keyframe_id_`?

**Comment by gaoxiang12** [comment]
Thanks for pointing it out! Fixed in commit [8de5911](https://github.com/gaoxiang12/slambook2/commit/8de591159a35cbf51be9a40c659a35c15ec157c7).
