### ISSUE TITLE
ch5  stereo 的基線單位是多少呢  ？感謝高老師

### ISSUE THREAD

**Issue by resplendent-star** [gaoxiang12/slambook2#50]
![基線](https://user-images.githubusercontent.com/41502003/69410480-1d612900-0d46-11ea-866b-1df244e9eacf.png)
/home/lzw/桌面/基線.png

**Comment by gaoxiang12** [comment]
是米，参见Kitti的传感器安装部分：http://www.cvlibs.net/datasets/kitti/setup.php Cam0到Cam1的距离，标定出来是0.57m左右。

**Comment by resplendent-star** [comment]
> 是米，见Kitti的传感器安装部分：[http:](http://www.cvlibs.net/datasets/kitti/setup.php) //www.cvlibs.net/datasets/kitti/setup.php Cam0到Cam1的距离，标定出来是0.57m左右。

感谢高老师的回复，我大概是想问，因为我看到后面计算点云三维坐标点的代码，就在思考，是不是点云坐标的单位取决于 前面 int  b=1.5；的单位，如果这里是1.5m 那么在pangolin 里面点云坐标单位就是 m，是否理解正确呢？

**Comment by resplendent-star** [comment]
> 是米，见Kitti的传感器安装部分：[http:](http://www.cvlibs.net/datasets/kitti/setup.php) //www.cvlibs.net/datasets/kitti/setup.php Cam0到Cam1的距离，标定出来是0.57m左右。

感谢高老师的回复，我大概是想问，因为我看到后面计算点云三维坐标点的代码，就在思考，是不是点云坐标的单位取决于前面int b = 1.5；的单位，如果这里是1.5m那么在pangolin里面点云坐标单位就是m，是否理解正确呢？
