### ISSUE TITLE
第九讲打开bundle_adjustment_g2o失败,symbol lookup error,undefined symbol

### ISSUE THREAD

**Issue by chubukeji** [gaoxiang12/slambook2#51]
编译可以通过，并没有报错，但是执行./bundle_adjustment_g2o ../problem-16-22106-pre.txt 时失败，错误如下：./bundle_adjustment_g2o: symbol lookup error: ./bundle_adjustment_g2o: undefined symbol:_ZN3g2o30OptimizationAlgorithmLevenbergC1ESt10unique_ptrINS_6SolverESt14default_deleteIS2_EE .求问这种问题应该怎么解决啊

**Comment by chubukeji** [comment]
应该是g2o版本的问题，之前六七讲用到g2o的地方也是同样错误。我只好把g2o换成了第一版教材里的版本，再把程序改成第一版的写法，就可以了。

**Comment by Stark-Chang** [comment]
关于高博《视觉slam十四讲》第二版中g2o库的
symbol lookup error: ./bundle_adjustment_g2o: undefined symbol: _ZN3g2o30OptimizationAlgorithmLevenbergC1ESt10unique_ptrINS_6SolverESt14default_deleteIS2_EE问题解决。
首先说一下我遇到的问题。第六讲时第一次使用g2o，当时安装的依赖：sudo apt-get install libqt4-dev qt4-qmake libqglviewer-dev libsuitesparse-dev libcxsparse3.1.2 libcholmod-dev第六、七讲的代码编译和运行都是没有问题的。直到第九讲《后端1》9.4实践用g2o求解BA。代码编译没有问题，但是最后执行可执行文件这一步时./bundle_adjustment_g2o data/problem-16-22106-pre.txt
报错：symbol lookup error: ./bundle_adjustment_g2o: undefined symbol:_ZN3g2o30OptimizationAlgorithmLevenbergC1ESt10unique_ptrINS_6SolverESt14default_deleteIS2_EE。
分析原因：中间发现我在ubuntu16.04上安装了qt5的依赖，导致qt4和qt5同时存在，qmake -v后发现版本是qt5的，qt5应该适用于高博第二版用的ubuntu18，而我是16，本身自带了qt4。因此我怀疑是cmake 过程中无法选择qt版本导致乱码。
解决步骤：
1.卸载qt5-qmake和qt5-default。然后qmake -v 确认版本是4.0左右的版本。
2.卸载g2o并安装高博第一版的g2o，然后修改代码中g2o配置的语法，模板代码取自高博从零开始一起学习SLAM | 理解图优化，一步步带你看懂g2o 
https://mp.weixin.qq.com/s?__biz=MzIxOTczOTM4NA==&mid=2247486858&idx=1&sn=ce458d5eb6b1ad11b065d71899e31a04&chksm=97d7e81da0a0610b1e3e12415b6de1501329920c3074ab5b48e759edbb33d264a73f1a9f9faf&scene=21#wechat_redirect
具体步骤
typedef g2o::BlockSolver< g2o::BlockSolverTraits<3,1> > Block;  // 每个误差项优化变量维度为3，误差值维度为1
// 第1步：创建一个线性求解器LinearSolver
Block::LinearSolverType* linearSolver = new g2o::LinearSolverDense<Block::PoseMatrixType>(); 
// 第2步：创建BlockSolver。并用上面定义的线性求解器初始化
Block* solver_ptr = new Block( linearSolver );      
// 第3步：创建总求解器solver。并从GN, LM, DogLeg 中选一个，再用上述块求解器BlockSolver初始化
g2o::OptimizationAlgorithmLevenberg* solver = new g2o::OptimizationAlgorithmLevenberg( solver_ptr );
// 第4步：创建终极大boss 稀疏优化器（SparseOptimizer）
g2o::SparseOptimizer optimizer;     // 图模型
optimizer.setAlgorithm( solver );   // 设置求解器
optimizer.setVerbose( true );       // 打开调试输出
3.然后代码编译运行都没有问题了，但g2o_vierwer出问题了。g2o_viewer 启动时报错（core dumped），Error in `g2o_viewer': realloc(): invalid pointer: 0x00007efeed2e5820。
解决步骤参考https://blog.csdn.net/abc_orange/article/details/81874218
不过该博文是基于qt5的，如果你是ubuntu16.04就对应改成qt4的，这个很简单就不多赘述了，博文里面讲的很详细。

**Comment by chubukeji** [comment]
。
