### ISSUE TITLE
ch5 stereovision  出现了一些奇怪的点云

### ISSUE THREAD

**Issue by resplendent-star** [gaoxiang12/slambook2#52]
代码除了更改了图片的路径和相机内参，其他都没有改变
`#include <iostream>
#include <opencv2/opencv.hpp>
#include <vector>
#include <string>
#include <Eigen/Core>
#include <pangolin/pangolin.h>
#include <unistd.h>

using namespace std;
using namespace Eigen;
using namespace cv;
// 文件路径
//string left_file = "./2_L.png";
//string right_file = "./2_R.png";
string left_file = "./im0.png";
string right_file = "./im1.png";

// 在pangolin中画图，已写好，无需调整
void showPointCloud(
        const vector<Vector4d, Eigen::aligned_allocator<Vector4d>> &pointcloud);

int main(int argc, char **argv) {

    // 内参
  //  double fx = 714.285, fy = 714.285, cx = 380, cy = 380;
    // 基线
   // double b = 1.5;
    double fx = 2076.037, fy = 2076, cx = 750, cy = 486;
    // 基线
   double b = 0.176;
    // 读取图像
    cv::Mat left = cv::imread(left_file, 0);
    cv::Mat right = cv::imread(right_file, 0);
    if(left.data==NULL)
    {cout<<"left image dont exist"<<endl;}
    if(right.data==NULL)
    {cout<<"right image dont exist"<<endl;}

    cv::Ptr<cv::StereoSGBM> sgbm = cv::StereoSGBM::create(
            0, 96, 9, 8 * 9 * 9, 32 * 9 * 9, 1, 63, 10, 100, 32);    // 神奇的参数
    cv::Mat disparity_sgbm, disparity;
    sgbm->compute(left, right, disparity_sgbm);
    disparity_sgbm.convertTo(disparity, CV_32F, 1.0 / 16.0f);

    // 生成点云
    vector<Vector4d, Eigen::aligned_allocator<Vector4d>> pointcloud;

    // 如果你的机器慢，请把后面的v++和u++改成v+=2, u+=2
    for (int v = 0; v < left.rows; v++)
        for (int u = 0; u < left.cols; u++) {
            if (disparity.at<float>(v, u) <= 0.0 || disparity.at<float>(v, u) >= 96.0) continue;

            Vector4d point(0, 0, 0, left.at<uchar>(v, u) / 255.0); // 前三维为xyz,第四维为颜色

            // 根据双目模型计算 point 的位置
            double x = (u - cx) / fx;
            double y = (v - cy) / fy;
            double depth = fx * b / (disparity.at<float>(v, u));
            point[0] = x * depth;
            point[1] = y * depth;
            point[2] = depth;

            pointcloud.push_back(point);
        }

    cv::namedWindow("disparity", CV_WINDOW_NORMAL);

    cv::imshow("disparity", disparity / 96.0);

    cv::waitKey(0);
    // 画出点云
    showPointCloud(pointcloud);
    return 0;

}

void showPointCloud(const vector<Vector4d, Eigen::aligned_allocator<Vector4d>> &pointcloud) {

if (pointcloud.empty()) {
cerr << "Point cloud is empty!" << endl;
return;
}

pangolin::CreateWindowAndBind("Point Cloud Viewer", 1024, 768);
glEnable(GL_DEPTH_TEST);
glEnable(GL_BLEND);
glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

pangolin::OpenGlRenderState s_cam(
        pangolin::ProjectionMatrix(1024, 768, 500, 500, 512, 389, 0.1, 1000),
        pangolin::ModelViewLookAt(0, -0.1, -1.8, 0, 0, 0, 0.0, -1.0, 0.0)
);

pangolin::View &d_cam = pangolin::CreateDisplay()
        .SetBounds(0.0, 1.0, pangolin::Attach::Pix(175), 1.0, -1024.0f / 768.0f)
        .SetHandler(new pangolin::Handler3D(s_cam));

while (pangolin::ShouldQuit() == false) {
glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

d_cam.Activate(s_cam);
glClearColor(1.0f, 1.0f, 1.0f, 1.0f);

glPointSize(2);
glBegin(GL_POINTS);
for (auto &p: pointcloud) {
glColor3f(p[3], p[3], p[3]);
glVertex3d(p[0], p[1], p[2]);
}
glEnd();
pangolin::FinishFrame();
usleep(5000);   // sleep 5 ms
}
return;
}
`

![im0](https://user-images.githubusercontent.com/41502003/69641955-0307b200-109c-11ea-91be-bd65a2d7c233.png)
这一张是立体图像的左眼
![im1](https://user-images.githubusercontent.com/41502003/69642629-08b1c780-109d-11ea-9e2e-45c7dffa5e9b.png)
右眼
![1](https://user-images.githubusercontent.com/41502003/69642152-4c580180-109c-11ea-92a1-38efa832e34c.png)

这一张是由代码算出来的视差图  

![2019-11-26 22-23-50屏幕截图](https://user-images.githubusercontent.com/41502003/69642470-c25c6880-109c-11ea-83fb-deb42797bf39.png)
这一张是点云的正视图

![2019-11-26 22-24-46屏幕截图](https://user-images.githubusercontent.com/41502003/69642525-d4d6a200-109c-11ea-9569-f3b29ccae951.png)

这一张是点云的俯视图  有一些奇奇怪怪的很长的的边线，请问这个该怎么办

cmake
//cmakelist

cmake_minimum_required(VERSION 3.15)
project(ch5_stereo)

set(CMAKE_CXX_STANDARD 11)

include_directories(${Eigen_INCLUDE_DIRS})
find_package(Pangolin REQUIRED)

# 寻找OpenCV库
find_package(OpenCV REQUIRED)
# 添加头文件
include_directories(${OpenCV_INCLUDE_DIRS})

add_executable(ch5_stereo main.cpp )

target_link_libraries(ch5_stereo ${OpenCV_LIBS} ${Pangolin_LIBRARIES})

**Comment by gaoxiang12** [comment]
BlockMatching在物体边界处和细长物体上表现是不稳定的，事实上本来就很难期望双目相机的点云能达到RGBD的效果。
