### ISSUE TITLE
ch5/stereoVision/stereoVision.cpp报错

### ISSUE THREAD

**Issue by fanofpal** [gaoxiang12/slambook2#56]
高老师您好，在编译ch5/stereoVision/stereoVision.cpp时出现了如下错误：
`slambook2/ch5/stereo/stereoVision.cpp:29:36: error: ‘create’ is not a member of ‘cv::StereoSGBM’`
`slambook2/ch5/stereo/stereoVision.cpp:32:11: error: ‘class cv::StereoSGBM’ has no member named ‘compute’`
查了很长时间都没有发现问题所在，ch5的其他代码都能够运行，因此opencv等库应该是正确安装了

**Comment by gaoxiang12** [comment]
推测是opencv版本问题，请问机器上安装的是什么版本？

**Comment by fanofpal** [comment]
@gaoxiang12 确实是opencv版本的问题！机器上安装了3.3.1，但是默认的版本还是2.4.9，在cmakelist里指定opencv使用3.3.1版本后问题得到了解决。谢谢高老师。
