### ISSUE TITLE
ch3: eigenGeometry.cpp 注解错误

### ISSUE THREAD

**Issue by amylmy** [gaoxiang12/slambook2#59]
https://github.com/gaoxiang12/slambook2/blob/e2f0c9def016bd95b08c27f1749825dfa18cea4e/ch3/useGeometry/eigenGeometry.cpp#L33

ZYX顺序，应该是yaw-pitch-roll？下一句的输出是正确的.

**Comment by gaoxiang12** [comment]
感谢指出，已修复。
