### ISSUE TITLE
CH6 中手写高斯牛顿的疑问

### ISSUE THREAD

**Issue by ss2lyf** [gaoxiang12/slambook2#68]
请问下高翔老师和各位小伙伴，为什么手写高斯牛顿的时候在计算H的时候要乘上噪声的方差的倒数呢？就是 Hessian = J^T W^{-1} J in Gauss-Newton，然后最后乘上的是inv_sigma，谢谢！

**Comment by gaoxiang12** [comment]
完整的Gauss-Newton要带上噪声的协方差来推导。你可以自己推一下这个过程，书里为了介绍方便就只讲了不带噪声协方差的版本。

**Comment by ss2lyf** [comment]
好的，非常感谢高翔老师

> 完整的Gauss-Newton要带上噪声的协方差来推导。你可以自己推一下这个过程，书里为了介绍方便就只讲了不带噪声协方差的版本。
