### ISSUE TITLE
海外党买书不方便，能不能在AMAZON上线PDF版本？

### ISSUE THREAD

**Issue by placeforyiming** [gaoxiang12/slambook2#70]
English pdf version is also fine!

**Comment by gaoxiang12** [comment]
抱歉前两天没看邮件，根据出版社的反馈，电子版应该会在几个月之后上京东。
如果着急需要的话，可以联系我邮箱，我可以提供审稿期间的版本。

**Comment by placeforyiming** [comment]
> 抱歉前两天没看邮件，根据出版社的反馈，电子版应该会在几个月之后上京东。
> 如果着急需要的话，可以联系我邮箱，我可以提供审稿期间的版本。

多谢高博！我找到了
