### ISSUE TITLE
关于ch12 mono dense_mapping 在极线上搜索的一个小问题

### ISSUE THREAD

**Issue by resplendent-star** [gaoxiang12/slambook2#80]
![github](https://user-images.githubusercontent.com/41502003/77227501-b6506580-6bbb-11ea-85cf-6022cdb4ca96.png)
![github2](https://user-images.githubusercontent.com/41502003/77227505-b9e3ec80-6bbb-11ea-8825-4566fb8898c7.jpg)

高老师您好,如果要使得每次在极线上只搜索一个pixel,是不是应该把l+=0.7改成 l+=1.0
理由如第二张图中我的简单推导
pc'-pc的范数应该为 1,所以k=1,因此每次l+=1比较合理
第一张图是代码的截图,第二张图是一个简单的推导过程

**Comment by gaoxiang12** [comment]
Hi, 这个参数影响不明显，步长小时比较的次数多一些，但是更精细一些。你可以改成1.0之后再试试效果。

**Comment by resplendent-star** [comment]
谢谢高老师回复------------------ 原始邮件 ------------------
发件人: "Xiang Gao"<notifications@github.com>
发送时间: 2020年3月23日(星期一) 上午8:57
收件人: "gaoxiang12/slambook2"<slambook2@noreply.github.com>;
抄送: "resplendent-star"<485434977@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [gaoxiang12/slambook2] 关于ch12 mono dense_mapping 在极线上搜索的一个小问题 (#80)




 
Hi, 这个参数影响不明显，步长小时比较的次数多一些，但是更精细一些。你可以改成1.0之后再试试效果。
 
&mdash;
