### ISSUE TITLE
ch11,高老师好,请问我如何把DBOW3编译为静态库(.a)呢,cmake 自动把它编译为  .so了,导致ch11代码无法运行

### ISSUE THREAD

**Issue by resplendent-star** [gaoxiang12/slambook2#81]
这是sudo make uninstall 的info
-- Install configuration: "Release"
-- Installing: /usr/local/lib/cmake/FindDBoW3.cmake
-- Installing: /usr/local/lib/cmake/DBoW3/DBoW3Config.cmake
-- Installing: /usr/local/lib/libDBoW3.so.0.0.1
-- Installing: /usr/local/lib/libDBoW3.so.0.0
-- Installing: /usr/local/lib/libDBoW3.so
-- Set runtime path of "/usr/local/lib/libDBoW3.so.0.0.1" to ""
-- Installing: /usr/local/include/DBoW3/BowVector.h
-- Installing: /usr/local/include/DBoW3/DBoW3.h
-- Installing: /usr/local/include/DBoW3/Database.h
-- Installing: /usr/local/include/DBoW3/DescManip.h
-- Installing: /usr/local/include/DBoW3/FeatureVector.h
-- Installing: /usr/local/include/DBoW3/QueryResults.h
-- Installing: /usr/local/include/DBoW3/ScoringObject.h
-- Installing: /usr/local/include/DBoW3/Vocabulary.h
-- Installing: /usr/local/include/DBoW3/exports.h
-- Installing: /usr/local/include/DBoW3/quicklz.h
-- Installing: /usr/local/include/DBoW3/timers.h
-- Installing: /usr/local/bin/demo_general
-- Set runtime path of "/usr/local/bin/demo_general" to ""
-- Installing: /usr/local/bin/create_voc_step0
-- Set runtime path of "/usr/local/bin/create_voc_step0" to ""
-- Installing: /usr/local/bin/create_voc_step1
-- Set runtime path of "/usr/local/bin/create_voc_step1" to ""
lzw@resplendent-star:~/3d_lib/DBow3-master/build$ 

这是clion的报错
/home/lzw/3d_lib/clion-2019.3.4/bin/cmake/linux/bin/cmake --build /home/lzw/resplendent_code/SLAMbook2/ch11/cmake-build-debug --target feature_training -- -j 4
make[3]: *** 没有规则可制作目标“/usr/local/lib/libDBoW3.a”，由“feature_training” 需求。 停止。
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/feature_training.dir/all' failed
make[2]: *** [CMakeFiles/feature_training.dir/all] Error 2
CMakeFiles/Makefile2:113: recipe for target 'CMakeFiles/feature_training.dir/rule' failed
make[1]: *** [CMakeFiles/feature_training.dir/rule] Error 2
Makefile:131: recipe for target 'feature_training' failed
make: *** [feature_training] Error 2

**Comment by JianmingTONG** [comment]
将https://github.com/rmsalinas/DBow3下载下来的CMakeLists.txt中
```
OPTION(BUILD_UTILS	"Set to OFF to not build utils" ON)
OPTION(USE_CONTRIB 	"Set to ON if contrib are installed" OFF)
OPTION(BUILD_SHARED_LIBS 	"Set to OFF to build static libraries" ON)
```
第三个改成OFF，如下，然后正常cmake安装即可
```
OPTION(BUILD_UTILS	"Set to OFF to not build utils" ON)
OPTION(USE_CONTRIB 	"Set to ON if contrib are installed" OFF)
OPTION(BUILD_SHARED_LIBS 	"Set to OFF to build static libraries" OFF)
```

**Comment by resplendent-star** [comment]
谢谢！------------------ 原始邮件 ------------------
发件人: "Jianming"<notifications@github.com>
发送时间: 2020年4月15日(星期三) 晚上10:55
收件人: "gaoxiang12/slambook2"<slambook2@noreply.github.com>;
抄送: "resplendent-star"<485434977@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [gaoxiang12/slambook2] ch11,高老师好,请问我如何把DBOW3编译为静态库(.a)呢,cmake 自动把它编译为  .so了,导致ch11代码无法运行 (#81)




 
将https://github.com/rmsalinas/DBow3下载下来的CMakeLists.txt中
 OPTION(BUILD_UTILS	"Set to OFF to not build utils" ON) OPTION(USE_CONTRIB 	"Set to ON if contrib are installed" OFF) OPTION(BUILD_SHARED_LIBS 	"Set to OFF to build static libraries" ON)  
第三个改成OFF，如下，然后正常cmake安装即可
 OPTION(BUILD_UTILS	"Set to OFF to not build utils" ON) OPTION(USE_CONTRIB 	"Set to ON if contrib are installed" OFF) OPTION(BUILD_SHARED_LIBS 	"Set to OFF to build static libraries" OFF)  
&mdash;

**Comment by TaylorGy** [comment]
由 @JianmingTONG 回答精简为如下流程：
```
$ mkdir build && cd build
$ cmake .. -DBUILD_SHARED_LIBS=OFF
$ make
$ sudo make install
```

**Comment by liubamboo** [comment]
@resplendent-star 请问你可以运行了吗？我按照上面的方法，重新make的时候出现如下错误：
/usr/local/lib/libDBoW3.a(Vocabulary.cpp.o)：在函数‘cv::operator<<(cv::FileStorage&, char const*)’中：
Vocabulary.cpp:(.text+0xb49)：对‘cv::operator<<(cv::FileStorage&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
/usr/local/lib/libDBoW3.a(Vocabulary.cpp.o)：在函数‘DBoW3::Vocabulary::load(cv::FileStorage const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
Vocabulary.cpp:(.text+0x3a16)：对‘cv::FileStorage::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const’未定义的引用
/usr/local/lib/libDBoW3.a(Vocabulary.cpp.o)：在函数‘DBoW3::Vocabulary::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const’中：
Vocabulary.cpp:(.text+0x8f81)：对‘cv::FileStorage::FileStorage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用

请问你知道如何解决吗？你的opencv版本是多少呢？

**Comment by liubamboo** [comment]
已解决，原因是由于我安装了多个版本的opencv，需要对DBoW和slam十四讲的CMakeLists.txt添加set(OpenCV_DIR "安装路径")

**Comment by gaoxiang12** [comment]
Closed.

**Comment by smallrain777** [comment]
> 已解决，原因是由于我安装了多个版本的opencv，需要对DBoW和slam十四讲的CMakeLists.txt添加set(OpenCV_DIR "安装路径")

直接把CH11的 CMAKELIST里面的OPENCV3.1改成4即可
