### ISSUE TITLE
Ch6 g2o shared library issue

### ISSUE THREAD

**Issue by hanzheteng** [gaoxiang12/slambook2#82]
When running `./g2oCurveFitting` on Ubuntu 18.04, I got the following error.
```
error while loading shared libraries: libg2o_core.so: cannot open shared object file: No such file or directory
```
The solution can be found in  https://github.com/gaoxiang12/slambook/issues/52 and https://github.com/gaoxiang12/slambook/issues/125. The same issue still exists in this repo. 

The issue #38 also mentioned the solution. Will submit a PR later on.

**Comment by yifanAptiv** [comment]
What I did is run LD_LIBRARY_PATH=/usr/local/lib ./g2oCurveFitting

**Comment by hanzheteng** [comment]
PR has been merged. Closing this issue.
